# Generated by Django 4.2.1 on 2023-05-22 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='academic_level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='formatting_style',
            field=models.CharField(default='APA', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='paper_title',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='sources',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='documents',
            field=models.FileField(default='default_document.pdf', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='folders',
            field=models.FileField(blank=True, default='default_folder.zip', upload_to='folders/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='images',
            field=models.FileField(blank=True, default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
