# Generated by Django 4.2.1 on 2023-05-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_order_academic_level_order_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('education', models.TextField()),
                ('documents', models.ImageField(blank=True, null=True, upload_to='writer_documents/')),
            ],
        ),
    ]
