# Generated by Django 4.2.1 on 2023-05-27 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_writerbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writerbid',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='writerbid',
            name='documents',
            field=models.FileField(upload_to='writer_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
